services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    user: '${UID:-1000}:${GID:-1000}'
    ports:
      - 3000:3000
      - 9229:9229 # Debug port
    volumes:
      - .:/app
    env_file:
      - path: .env
        required: true
    depends_on:
      message-brocker:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  message-brocker:
    image: rabbitmq:4.0-rc-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    user: ${RABBITMQ_DEFAULT_USER}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  mongodb:
    image: mongo:8.0
    entrypoint: ['mongod', '--bind_ip_all', '--replSet', 'rs0']
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  mongodb-init:
    image: mongo:8.0
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_INITDB_DATABASE: dead-letter-queue-example
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./setup.sh:/scripts/setup.sh
    entrypoint: ['/scripts/setup.sh']

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb/dead-letter-queue-example
      - PORT=8082
    ports:
      - '8082:8082'
    restart: unless-stopped
    depends_on:
      - mongodb
